version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.21
    commands:
      - echo "Verifying Go installation..."
      - go version

  pre_build:
    commands:
      - echo "Fetching dependencies..."
      - go mod download
      - go mod verify
      - mkdir -p dist/static
      - mkdir -p dist/templates

  build:
    commands:
      - GOOS=linux GOARCH=amd64 go build -o dist/my-web-app main.go
      - cp static/style.css dist/static/
      - cp templates/*.html dist/templates/

  post_build:
    commands:
      - cd dist && find . -type f -exec sha256sum {} \; > checksums.txt

artifacts:
  files:
    - '**/*'
    - checksums.txt
  base-directory: dist
  discard-paths: no
